# Site Settings
# Access using {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like.
title:      Steven Nydick
email:      swnydick@gmail.com
work_email: nydic001@umn.edu
cell_phone: 610-804-5448
description: >
  Psychometrician, Data Scientist, R Programmer
baseurl: ""                          # the subpath of your site, e.g. /blog
url:     "http://swnydick.github.io" # the base hostname & protocol for your site, e.g. http://example.com

social_sites:
  github:   swnydick
  linkedin: steven-nydick
  facebook: swnydick

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
# theme: minima
plugins:
  - jekyll-feed

# Exclude Settings (change?)
exclude:
  - Gemfile
  - Gemfile.lock
